In [3]:
import numpy as np


matrix = np.array([[1, 0.2, 0.5], [0.2, 1, 0.8], [0.5, 0.8, 1]])


In [9]:
#a,
#inversion of the matrix
result = np.transpose(matrix)
print(result)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [5]:

#b,
#Determinant of a matrix
determinant = np.linalg.det(matrix)
print(determinant)

0.2299999999999999


In [6]:
#c,
#Matrix decomposition
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(eigenvalues)
print(eigenvectors)


[2.04100779 0.82188052 0.13711169]
[[-0.43721717 -0.85359707 -0.28321933]
 [-0.59931898  0.51133314 -0.61591816]
 [-0.67056536  0.09955128  0.73514055]]


In [11]:
#d,
#transforming a matrix
result= np.sin(matrix)
print( result)

[[0.84147098 0.19866933 0.47942554]
 [0.19866933 0.84147098 0.71735609]
 [0.47942554 0.71735609 0.84147098]]
